# Generated by Django 3.2.9 on 2021-11-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('contact_as', models.CharField(choices=[('cus', 'A Customer'), ('win', 'A Winery')], max_length=1024)),
                ('contact_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
