# Generated by Django 3.2.9 on 2021-11-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_options',
            field=models.BooleanField(default=True),
        ),
    ]
