# Generated by Django 3.2.9 on 2021-11-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_case_case_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_options',
        ),
        migrations.AddField(
            model_name='case',
            name='has_type',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
